name: flutter100day
description: A Flutter learning application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"
flutter_native_splash:
  image: assets/images/splash.png
  color: "#ffffff"
  ardroid: true
  fullscreen: true
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  transparent_image: ^2.0.0
  fluttertoast: ^8.0.8
  flutter_swiper: ^1.1.6
  flutter_native_splash: ^1.3.1
  flutter_datetime_picker: ^1.5.1
  date_format: ^2.0.4
  webview_flutter: ^2.2.0
  flutter_inappwebview: ^5.3.2
  flutter_smart_dialog: ^3.0.0
  awesome_dialog: ^2.1.1
  url_launcher: ^6.0.12
  dio: ^4.0.1
  flutter_easyloading: ^3.0.3
  flutter_spinkit: ^5.1.0
  video_player: ^2.2.6
  fijkplayer: 0.10.0
  fijkplayer_skin: 2.2.8
  audioplayers: ^0.20.1
  provider: ^6.0.1
  flutter_neumorphic: ^3.1.1
  assets_audio_player: ^3.0.3+6
  shared_preferences: ^2.0.8
  http: ^0.13.4
  event_bus: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/index.html
    - assets/css/
    - assets/img/
    - assets/js/
    - assets/audios/
    - assets/audio2.mp3
    - assets/messenger.mp3
  fonts:
    - family: AssetAudioPlayer
      fonts:
        - asset: assets/fonts/AssetAudioPlayer.ttf



  # An image assets can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the assets and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - assets: fonts/Schyler-Regular.ttf
  #       - assets: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - assets: fonts/TrajanPro.ttf
  #       - assets: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
